### ISSUE TITLE
Search for driver in local folder

### ISSUE THREAD

**Issue by steom** [DaveSpe/win_driver_remover#1]

**Comment by DaveSpe** [comment]
This does not iterate through any folders and only looks for installed drivers using deployment image servicing and management (dism). It only picks up drivers that are currently installed on your system.

I use this to clean drivers out when I swap the primary Windows drive and put it in new hardware. 
I run the scrip remove any hardware drivers and shutdown. I used this to clean my primary OS when moving from an AMD system to a intel system. I only slightly modified it from the original to give me the option to select which drivers I want to remove, vs the original which removed all 3rd party drivers. It works well for this use case. 

Any driver that exists in a folder and is not installed can be removed manually. I suggest you look at software such as CCleaner or something similar, this should be able to clean the registry and any left over drivers. I think.

If you want to fork, and add this feature set I'd be more than happy to merge.
